DOTFILES="/Users/fgasperi/Code/dotfiles"

# command line editing
bindkey -v # vi emulation mode
bindkey '^R' history-incremental-search-backward
bindkey -M vicmd '^U' clear-screen
bindkey -M viins '^U' clear-screen
bindkey -M viins 'jk' vi-cmd-mode

# vim keybindings for info reading
alias info='info --vi-keys'

# QUESTION: is this being used? why is it necessary?
# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# aliases
## utilities
alias ccat='pygmentize -g'
## shortcut
alias reload!='source ~/.zshrc'
alias config='$EDITOR ~/.zshrc.pre-oh-my-zsh'

# shorcuts

function cherry-picky() {
  git log -1 -p $1 $2 | patch -p1
}
function gi() {
  curl -L -s https://www.gitignore.io/api/"$@" ;
}

# autojump
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  source /etc/profile.d/autojump.zsh
elif [[ "$OSTYPE" == "darwin"* ]]; then
  [ -f $(brew --prefix)/etc/profile.d/autojump.sh ] && $(brew --prefix)/etc/profile.d/autojump.sh
fi

function scast {
  ffmpeg -f x11grab -video_size 1920x1080 -framerate 25 -i $DISPLAY -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac $1
}

source $DOTFILES/zsh/facebook.sh
