export EDITOR="vim"

# Command line editing
bindkey -v # vi emulation mode
bindkey '^R' history-incremental-search-backward
bindkey -M vicmd '^U' clear-screen
bindkey -M viins '^U' clear-screen
bindkey -M viins 'jk' vi-cmd-mode

# aliases
## shortcut
alias reload!='source ~/.zshrc'
alias config='vim ~/.zshrc'
alias l='ls -lah'

# Pull a default git ignore file for a programming language
function gi() {
  language=$1
  curl -L -s https://www.gitignore.io/api/"$language" ;
}
